### ISSUE TITLE
Our Team section

### ISSUE THREAD

**Issue by Pranshu1902** [Android-Club-VITC/AC-Website-NextJs#15]
Build the contact section in the `/app/(Home)/Section3.tsx`

![image](https://github.com/Android-Club-VITC/AC-Website-NextJs/assets/70687348/f18e1269-91e7-4dfb-844a-605e0e7375d5)

**Comment by gauthking** [comment]
i would like to work on this section..

**Comment by Pranshu1902** [comment]
@gauthking go ahead
