### ISSUE TITLE
Request Permission to Work on "Our Work And Value" Section

### ISSUE THREAD

**Issue by chendjou237** [Android-Club-VITC/AC-Website-NextJs#3]
I would like to request permission to work on the "Our Work And Value" section of the AC-Website-NextJs application. This section of the app plays a crucial role in showcasing our organization's achievements, mission, and values, and I believe I can contribute positively to its development and enhancement. I will like it to have the label of the Hacktober Fest

**Comment by Pranshu1902** [comment]
@chendjou237 I have assigned the issue to you, you can start working on it
