### ISSUE TITLE
Feature:  About Page 

### ISSUE THREAD

**Issue by Surya-V-28** [Android-Club-VITC/AC-Website-NextJs#5]
Thank you for sharing the project, 

I would like to work on the about page, if you have any UI design  please share it , 

please assign this under hacktober  fest

**Comment by Pranshu1902** [comment]
@Surya-V-28 I have already assigned the issue of the About Page in another issue, can you take up some other page like Our Teams page?
Figma: https://www.figma.com/file/ydL7ac5aGDjrXUMtV7ggqp/Android-Club-Website?type=design&node-id=0-1&mode=design&t=81d9zXeihT6h6Xcy-0

**Comment by Surya-V-28** [comment]
@Pranshu1902, Sure, I will take contact page . do you want me to make new Issues for that ?

**Comment by Pranshu1902** [comment]
@Surya-V-28 I have raised a new issue, just send a request to assign it you over there and I will assign it to you

**Comment by Pranshu1902** [comment]
Closing this issue for now
